### ISSUE TITLE
[SUB-EPIC] Contributor Levels + Discount Code Use Tracking

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/api.gatsbyjs.org#13]
> **NOTE:** This issue is an epic, which bundles up lots of related issues into a single goal. If you have the [free ZenHub extension](https://www.zenhub.com/), you’ll be able to see overall progress and related issues, as well as a "board view" that shows this epic from a bird's-eye view.

This is a sub-epic of https://github.com/gatsbyjs/store.gatsbyjs.org/issues/168
### Who will own this?

**Area of Responsibility:** Ecosystem

Role                | Name                       | RACI
------------------- | -------------------------- | -------------------------------
**AoR owner**       | @amberleyromo              | _Consulted about the epic_
**Domain owner**    | @amberleyromo              | _Informed about epic_
**Project manager** | @jlengstorf                | _Responsible for setting epic tasks_
**Tech lead**       | @amberleyromo              | _Accountable for setting guidelines for epic_
**Contributors**    | @amberleyromo @jlengstorf  | _Responsible for completing assigned tasks_

### Summary

Extend the Gatsby store API to support multiple levels of contributor rewards, as well as keeping track of whether or not a contributor has used a given discount code.

### How will this impact Gatsby?

**Domains**

- Gatsby store

### Goals

1. Add support for returning multiple discount codes for differing levels of contribution
2. Add a flag for whether or not the discount code was already used by the contributor

### How will we know this epic is a success?

We know this is a success when the API returns sufficient data to complete the parent epic.

**Comment by jlengstorf** [comment]
Really messy sketch of what we need to accomplish with this redesign (also [time-lapsed](https://twitter.com/jlengstorf/status/1062873146108272642)):

![img_20181114_164137](https://user-images.githubusercontent.com/163561/48523815-c40d1280-e832-11e8-8497-d4adc1f16742.jpg)

**Comment by jlengstorf** [comment]
We want to have multiple levels of contribution rewards:
- 1–4 PRs = Level 1 ($10 item)
- 5+ PRs = Level 2 ($30 item)

In order to do that, we need two coupon codes. Associate those coupon with accounts in Shopify.

## Current 
1. Go to store
2. Log in with GitHub
3. If you have PRs, we show a "claim your swag" form
4. Submit to create a Shopify customer w/your email
5. Shopify customer is tagged with `contributor`
6. We show a discount code
7. Discount code only works for customers who have the `contributor` tag

## Next

Mostly the same, except:

1. If you have 5 or more PRs, we need to add a second tag, `level-2`
2. If you have `level-2`, we need to return the second discount code

**Comment by amberleyromo** [comment]
Whimsical link: https://whimsical.co/92eWc861LQTMLbcYN64J1h

**Comment by jlengstorf** [comment]
Done!
