### ISSUE TITLE
Cold start on Lambda seems to trigger CORS errors

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/api.gatsbyjs.org#18]
We have intermittent CORS failures, and the flow seems to be something like this:

1. Visit the store
2. Log in
3. The "open issues" section errors out with CORS errors
4. Reload the page
5. No CORS error; open issues load just fine

I have no proof, but my suspicion is that this is an issue with AWS Lambda "cold starts". I'm not sure if there's a for-real fix, but the smash-it-with-a-hammer fix is to keep the lamda warm.

Looks like Serverless has a plugin for this (see [this tutorial](https://serverless.com/blog/keep-your-lambdas-warm/)), so we just need to put this in place.

**Comment by jlengstorf** [comment]
The would _only_ be applied to the `/graphql` lambda, because the Playground isn't loaded in production.

**Comment by samovertonjr** [comment]
I'll try and help with the issue.

**Comment by jlengstorf** [comment]
@samovertonjr All yours! Let me know if you have any questions. 💪💜

**Comment by samovertonjr** [comment]
@jlengstorf I think I have it all figured out. How would I go about testing everything before I submit the PR.

**Comment by jlengstorf** [comment]
@samovertonjr unfortunately, the only way to test is to set up all the private tokens, which would mean setting up your own Shopify and GitHub stuff. If the automated tests are passing, I'm happy to do that manual testing so you don’t have to do that work.

**Comment by samovertonjr** [comment]
Ok I'll just get the pr up. Thanks
