### ISSUE TITLE
Free swag codes can be used multiple times

### ISSUE THREAD

**Issue by chadfawcett** [gatsbyjs/api.gatsbyjs.org#8]
As I was discovering the bug resolved in #7, I noticed that I was able to apply the promo code again to get free swag. I didn't fully complete the checkout, so I don't know if there would have been an error, but I would have expected Shopify to have warned about an invalid code.

A bit of research revealed shopify has a [`once_per_customer`](https://help.shopify.com/en/api/reference/discounts/pricerule#once-per-customer-property) option for their `PriceRules`. I wanted to point this out incase you don't have it set.

**Comment by jlengstorf** [comment]
The discount code is currently set to only allow one use per customer. They Shopify interface is a little weird about this, and sometimes doesn't update right away, but so far it's been good at only allowing a single use.

Thanks for checking this, tough! We really appreciate it.

**Comment by chadfawcett** [comment]
Turns out I was still one step away from checking out. I hadn't filled in my shipping information. Once I did that, Shopify removed the discount.
