### ISSUE TITLE
Instructions on how to start the project locally is out of date

### ISSUE THREAD

**Issue by chadfawcett** [gatsbyjs/api.gatsbyjs.org#9]
* Clone url is out of date/invalid
* Might be worthwhile explaining the environment variables needed

https://github.com/gatsbyjs/api.gatsbyjs.org/blob/f2d7f845b162ed5f9d75bc7d5f1c99c31f56bb39/README.md#step-1-start-the-api-locally

**Comment by jlengstorf** [comment]
Good call. Will add this to the TODO list.

**Comment by chadfawcett** [comment]
Well the README doesn't mention anything about the `.env.EXAMPLE` file. I think each variable should at least have a short description, if not a step by step guide on acquiring them (getting github and shopify tokens, etc).

**Comment by PSalant726** [comment]
Ok, I added a table with some short variable descriptions. I did the best I could with limited context. Definitely open to feedback on the PR!
